# Description: This playbook installs Python and related tools on Ubuntu
#
# Example usage against localhost: sudo ansible-playbook ./python.playbook.yml
# Example usage against remote host: sudo ansible-playbook ./python.playbook.yml --extra-vars "target_host=[remote host]"

- name: Install Python
  hosts: "{{ target_host | default('localhost') }}"
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install venvs
      apt:
        name: python3-venv
        state: present
